POST http://localhost:8080/healthcheck

###
POST http://localhost:8080/debug/vars

###

GET http://localhost:8080/metrics
Content-Type: application/json

###

POST http://localhost:8080/api/search
Content-Type: application/json

{
  "search": "grafana",
  "page": 1,
  "per_page": 10
}

###

DELETE http://localhost:8080/api/delete
Content-Type: application/json

{
  "file_id": "64c988af-a011-4c3f-aef4-3eb070ba5efb.jpg"
}


###

# Test with (echo -n '{"page": 1, "per_page": 1, "search_file": "'; base64 -i test.jpg; echo '"}') | curl -H "Content-Type: application/json" -d @-  http://localhost:8080/api/image-search
POST http://localhost:8080/api/image-search
Content-Type: application/json

{
  "search_file": "/9j/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIAAgAFgMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP7+KKKKACiiigD/2Q==",
  "page": 1,
  "per_page": 10
}

