version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    environment:
      - S3_ENDPOINT
      - S3_KEY
      - S3_SECRET
      - S3_BUCKET
      - S3_PUBLIC
      - DB_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME
      - TEST_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME
      - OLLAMA_URL
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
      minio:
        condition: service_started
    logging: &default_logging
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  migrate:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    volumes:
      - ./migrations:/app/migrations
    environment:
      - DB_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME?sslmode=disable
    logging: *default_logging
    depends_on:
      db:
        condition: service_healthy
    entrypoint: sh -c 'migrate -database="$${DB_DSN}" -path=./migrations up'

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DBPASS
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBNAME
      PGUSER: $DBUSER
      PGDATABASE: $DBNAME
    logging: *default_logging
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=$S3_KEY
      - MINIO_ROOT_PASSWORD=$S3_SECRET
      - MINIO_DEFAULT_BUCKETS=$S3_BUCKET:public
    logging: *default_logging
volumes:
  db-data:
    driver: local
  minio-data:
    driver: local
