version: "3.9"
services:
  app:
    image: ghcr.io/elnoro/indexer
    restart: always
    environment:
      - S3_ENDPOINT
      - S3_KEY
      - S3_SECRET
      - S3_BUCKET
      - S3_PUBLIC
      - DB_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DBPASS
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBNAME
volumes:
  db-data:
    driver: local
