version: "3.9"
services:
  app:
    image: ghcr.io/elnoro/indexer
    restart: always
    container_name: indexer_app
    environment:
      - S3_ENDPOINT
      - S3_KEY
      - S3_SECRET
      - S3_BUCKET
      - S3_PUBLIC
      - DB_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    logging: &default_logging
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  migrate:
    image: ghcr.io/elnoro/indexer
    container_name: indexer_migrate
    environment:
      - DB_DSN=postgres://$DBUSER:$DBPASS@db/$DBNAME?sslmode=disable
    logging: *default_logging
    depends_on:
      db:
        condition: service_healthy
    entrypoint: sh -c '/service/migrate -database="$${DB_DSN}" -path=./migrations up'

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DBPASS
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBNAME
      PGUSER: $DBUSER
      PGDATABASE: $DBNAME
    logging: *default_logging
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
